services:
  postgres:
    image: postgres:16
    container_name: postgres-webserver
    restart: unless-stopped
    environment:
      POSTGRES_DB: webserver_db
      POSTGRES_USER: jrdevangel
      POSTGRES_PASSWORD: iMacniaco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: